"""Render an assembled report to Markdown and standalone HTML.

Markdown is the exchange format (it pastes into Notion, Google Docs and IC
templates); HTML is the shareable artefact.  Both are produced from the same
structure so they cannot drift.
"""

from __future__ import annotations

import datetime as dt
import html
from typing import Any

from markdown_it import MarkdownIt

from app.core.enums import CredibilityBand
from app.reporting.builder import BuiltReport

_md = MarkdownIt("commonmark", {"html": False, "linkify": True}).enable("table")

BAND_LABEL = {
    CredibilityBand.STRONG: "Strong",
    CredibilityBand.MODERATE: "Moderate",
    CredibilityBand.LIMITED: "Limited",
    CredibilityBand.WEAK: "Weak",
    CredibilityBand.UNSUPPORTED: "Unsupported",
}

BAND_COLOR = {
    CredibilityBand.STRONG: "#15803d",
    CredibilityBand.MODERATE: "#0369a1",
    CredibilityBand.LIMITED: "#a16207",
    CredibilityBand.WEAK: "#c2410c",
    CredibilityBand.UNSUPPORTED: "#b91c1c",
}


def render_markdown(
    report: BuiltReport,
    *,
    company_name: str | None = None,
    document_name: str | None = None,
    generated_at: dt.datetime | None = None,
    degraded: bool = False,
    scorecard: dict[str, Any] | None = None,
) -> str:
    generated_at = generated_at or dt.datetime.now(dt.UTC)
    band = report.overall_band

    lines: list[str] = [
        f"# {report.title}",
        "",
        "> **Draft for Investment Committee — generated by BioIntel.** This is a first-draft "
        "scientific due-diligence analysis produced by automated claim extraction and "
        "literature retrieval. It requires review by a qualified scientific advisor before "
        "it informs an investment decision.",
        "",
    ]

    if degraded:
        lines.extend(
            [
                "> ⚠️ **Degraded run.** No language-model provider was configured, so this "
                "analysis was produced by deterministic lexical rules. Interpretation of "
                "figures, semantic evidence adjudication and narrative synthesis were not "
                "performed.",
                "",
            ]
        )

    lines.extend(
        [
            "| | |",
            "|---|---|",
            f"| **Company** | {company_name or '—'} |",
            f"| **Source document** | {document_name or '—'} |",
            f"| **Generated** | {generated_at.strftime('%Y-%m-%d %H:%M UTC')} |",
            f"| **Scientific credibility** | **{report.overall_score:.1f} / 100** "
            f"({BAND_LABEL.get(band, band.value)}) |",
            f"| **Assessment confidence** | {report.confidence:.2f} |",
        ]
    )
    if scorecard:
        lines.append(
            f"| **IC recommendation** | {_humanise(scorecard.get('recommendation', ''))} |"
        )
    lines.extend(
        [
            "",
            "## Executive Summary",
            "",
            report.executive_summary.strip(),
            "",
        ]
    )

    if scorecard:
        lines.extend(_render_scorecard(scorecard, report.dimension_narratives))

    for section in sorted(report.sections, key=lambda s: s.get("order", 0)):
        lines.extend([f"## {section['heading']}", "", section["body_markdown"].strip(), ""])
        so_what = (section.get("so_what") or "").strip()
        if so_what:
            lines.extend([f"> **So what:** {so_what}", ""])
        confidence = (section.get("confidence") or "").strip()
        if confidence:
            reason = (section.get("confidence_reason") or "").strip()
            lines.extend(
                [
                    f"_Confidence: **{confidence}**" + (f" — {reason}" if reason else "") + "_",
                    "",
                ]
            )

    if report.top_questions:
        lines.extend(_render_top_questions(report.top_questions))

    lines.extend(["## Recommendation", "", report.recommendation.strip(), ""])

    if report.recommendation_drivers:
        # Traceability: the reader can audit the verdict against the evidence
        # states that produced it without rereading the memo.
        lines.extend(
            [
                "**This recommendation follows from:**",
                "",
                *(f"- {driver}" for driver in report.recommendation_drivers),
                "",
            ]
        )

    if report.confidence_reasons:
        lines.extend(
            [
                f"**Why assessment confidence is {report.confidence:.2f}.** Confidence is a "
                "statement about how much could be checked, not about how good the science "
                "is — the two move independently.",
                "",
                *(f"- {reason}" for reason in report.confidence_reasons),
                "",
            ]
        )

    if report.citations:
        lines.extend(["## References", ""])
        for citation in report.citations:
            lines.append(_citation_line(citation))
        lines.append("")

    if report.limitations:
        lines.extend(["## Limitations of This Analysis", ""])
        lines.extend(f"- {limitation}" for limitation in report.limitations)
        lines.append("")

    lines.extend(
        [
            "---",
            "",
            "_BioIntel produces evidence-linked first drafts. Every claim above is traceable "
            "to a page of the source document, and every external citation to a retrieved "
            "record. Statements marked as BioIntel inference are analysis, not source facts._",
        ]
    )
    return "\n".join(lines)


def _citation_line(citation: dict[str, Any]) -> str:
    ref = citation.get("ref", "")
    if ref.startswith("C"):
        page = citation.get("page_number")
        quote = (citation.get("quote") or citation.get("statement") or "").strip()
        return f'- **[{ref}]** Source document, page {page}: "{quote}"'

    title = citation.get("title") or "Untitled record"
    label = citation.get("citation_label") or ""
    url = citation.get("url")
    journal = citation.get("journal")
    year = citation.get("year")
    venue = " · ".join(str(v) for v in (journal, year) if v)
    suffix = f" <{url}>" if url else ""
    return f"- **[{ref}]** {title}. {venue} ({label}).{suffix}".replace(" ()", "")


def render_html(
    report: BuiltReport,
    *,
    company_name: str | None = None,
    document_name: str | None = None,
    generated_at: dt.datetime | None = None,
    degraded: bool = False,
    scorecard: dict[str, Any] | None = None,
) -> str:
    markdown = render_markdown(
        report,
        company_name=company_name,
        document_name=document_name,
        generated_at=generated_at,
        degraded=degraded,
        scorecard=scorecard,
    )
    body = _md.render(markdown)
    band = report.overall_band
    accent = BAND_COLOR.get(band, "#334155")

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(report.title)}</title>
<style>
  :root {{ color-scheme: light dark; --accent: {accent}; }}
  * {{ box-sizing: border-box; }}
  body {{
    font: 16px/1.65 ui-serif, Georgia, "Times New Roman", serif;
    max-width: 46rem; margin: 0 auto; padding: 3rem 1.5rem 6rem;
    color: #111827; background: #ffffff;
  }}
  h1 {{ font-size: 2rem; line-height: 1.2; margin: 0 0 1.5rem; letter-spacing: -0.02em; }}
  h2 {{
    font-size: 1.3rem; margin: 2.75rem 0 0.75rem; padding-bottom: 0.35rem;
    border-bottom: 2px solid var(--accent); letter-spacing: -0.01em;
  }}
  h3 {{ font-size: 1.05rem; margin: 1.75rem 0 0.5rem; }}
  p, li {{ margin: 0 0 0.85rem; }}
  blockquote {{
    margin: 1.5rem 0; padding: 0.85rem 1.15rem; border-left: 4px solid var(--accent);
    background: #f8fafc; font-size: 0.94rem; font-family: ui-sans-serif, system-ui, sans-serif;
  }}
  table {{ border-collapse: collapse; width: 100%; margin: 1.25rem 0; font-size: 0.92rem;
           font-family: ui-sans-serif, system-ui, sans-serif; }}
  th, td {{ border: 1px solid #e2e8f0; padding: 0.5rem 0.7rem;
           text-align: left; vertical-align: top; }}
  th {{ background: #f1f5f9; font-weight: 600; }}
  code {{ font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.88em;
          background: #f1f5f9; padding: 0.1em 0.35em; border-radius: 3px; }}
  a {{ color: var(--accent); }}
  hr {{ border: none; border-top: 1px solid #e2e8f0; margin: 3rem 0 1.5rem; }}
  @media (prefers-color-scheme: dark) {{
    body {{ background: #0b0f19; color: #e5e7eb; }}
    blockquote {{ background: #111827; }}
    th {{ background: #111827; }}
    th, td {{ border-color: #1f2937; }}
    code {{ background: #111827; }}
  }}
  @media print {{
    body {{ max-width: none; padding: 0; }}
    h2 {{ page-break-after: avoid; }}
  }}
</style>
</head>
<body>
{body}
</body>
</html>
"""


def _render_scorecard(
    scorecard: dict[str, Any], narratives: list[dict[str, Any]] | None = None
) -> list[str]:
    """The scorecard, with every score explaining itself.

    Rendered by BioIntel rather than written by the model, so the numbers and
    the reasons given for them come from the same computation. A dimension
    that shows a number without the findings behind it is an assertion; one
    whose explanation was written separately from its score will eventually
    contradict it.
    """
    dimensions = scorecard.get("dimensions") or []
    if not dimensions:
        return []

    by_dimension = {n["dimension"]: n for n in (narratives or [])}

    lines = [
        "## Investment Committee Scorecard",
        "",
        (
            "Scores are computed deterministically from the claim-level analysis. "
            "*Not assessed* means no claim bore on the dimension — a gap in the deck. "
            "*n/a* means the dimension does not apply to this kind of company."
        ),
        "",
        "| Dimension | Score | Band | Confidence | What it answers |",
        "|---|---|---|---|---|",
    ]
    for dimension in dimensions:
        score = dimension.get("score")
        if isinstance(score, int | float):
            score_cell = f"**{score:.0f}**/100"
        else:
            score_cell = "n/a" if dimension.get("applicable") is False else "—"
        band = _humanise(dimension.get("band") or "not assessed")
        confidence = _humanise(dimension.get("confidence_band") or "—")
        lines.append(
            f"| {dimension.get('label', '')} | {score_cell} | {band} | {confidence} | "
            f"{dimension.get('question', '')} |"
        )

    lines.extend(
        [
            "",
            f"**Company archetype:** {_humanise(scorecard.get('archetype', 'unknown'))} — "
            "dimension weighting is set by archetype, because a platform company and a "
            "single-asset company do not carry the same risks.",
            "",
        ]
    )

    # Every assessed dimension explains itself, from the evidence graph.
    scored = [
        d
        for d in dimensions
        if isinstance(d.get("score"), int | float) and by_dimension.get(d.get("dimension"))
    ]
    if scored:
        lines.extend(["### Why each dimension scored what it did", ""])
        for dimension in sorted(scored, key=lambda d: d.get("score") or 0.0):
            narrative = by_dimension[dimension["dimension"]]
            lines.append(
                f"**{narrative['label']} — {narrative['score']:.0f}/100** "
                f"({_humanise(narrative.get('band') or '')}, "
                f"confidence {_humanise(narrative.get('confidence_band') or '')})"
            )
            lines.append("")
            lines.extend(f"- {driver}" for driver in narrative.get("drivers", []))
            reasons = narrative.get("confidence_reasons") or []
            if reasons and narrative.get("confidence_band") != "high":
                lines.append(f"- _Confidence:_ {reasons[0]}")
            move = narrative.get("what_would_move_it")
            if move:
                lines.append(f"- _Would move it:_ {move}")
            lines.append("")

    not_applicable = [d for d in dimensions if d.get("applicable") is False]
    if not_applicable:
        lines.extend(
            [
                "### Dimensions that do not apply",
                "",
                "This company is not developing a medical product, so these axes would "
                "produce numbers that look like findings but measure nothing:",
                "",
                *(f"- {d.get('label')}" for d in not_applicable),
                "",
            ]
        )

    return lines


def _render_top_questions(questions: list[dict[str, Any]]) -> list[str]:
    """The five questions worth asking, ranked by what their answers change.

    A list of fifteen good questions is a way of not choosing. These are
    ordered by expected impact on the decision, computed from the evidence
    state of the claims each one would resolve.
    """
    lines = [
        "## Diligence Priorities",
        "",
        "Ranked by how much the answer would move the investment decision — a question "
        "attached to a contradicted thesis-critical claim can change the recommendation; "
        "one attached to a corroborated peripheral claim cannot.",
        "",
    ]
    for item in questions:
        lines.append(f"**{item['rank']}. {item['question']}**")
        lines.append("")
        lines.append(f"- Why it ranks here: {item['why_it_matters']}")
        if item.get("what_good_looks_like"):
            lines.append(f"- A good answer contains: {item['what_good_looks_like']}")
        if item.get("priority"):
            lines.append(f"- Priority: {_humanise(item['priority'])}")
        lines.append("")
    return lines


def _humanise(value: str) -> str:
    return str(value).replace("_", " ").strip().capitalize() if value else "—"
