"""Render an assembled report to Markdown and standalone HTML.

Markdown is the exchange format (it pastes into Notion, Google Docs and IC
templates); HTML is the shareable artefact.  Both are produced from the same
structure so they cannot drift.
"""

from __future__ import annotations

import datetime as dt
import html
from typing import Any

from markdown_it import MarkdownIt

from app.core.enums import CredibilityBand
from app.reporting.builder import BuiltReport

_md = MarkdownIt("commonmark", {"html": False, "linkify": True}).enable("table")

BAND_LABEL = {
    CredibilityBand.STRONG: "Strong",
    CredibilityBand.MODERATE: "Moderate",
    CredibilityBand.LIMITED: "Limited",
    CredibilityBand.WEAK: "Weak",
    CredibilityBand.UNSUPPORTED: "Unsupported",
}

BAND_COLOR = {
    CredibilityBand.STRONG: "#15803d",
    CredibilityBand.MODERATE: "#0369a1",
    CredibilityBand.LIMITED: "#a16207",
    CredibilityBand.WEAK: "#c2410c",
    CredibilityBand.UNSUPPORTED: "#b91c1c",
}


def render_markdown(
    report: BuiltReport,
    *,
    company_name: str | None = None,
    document_name: str | None = None,
    generated_at: dt.datetime | None = None,
    degraded: bool = False,
    scorecard: dict[str, Any] | None = None,
) -> str:
    generated_at = generated_at or dt.datetime.now(dt.UTC)
    band = report.overall_band

    lines: list[str] = [
        f"# {report.title}",
        "",
        "> **Draft for Investment Committee — generated by BioIntel.** This is a first-draft "
        "scientific due-diligence analysis produced by automated claim extraction and "
        "literature retrieval. It requires review by a qualified scientific advisor before "
        "it informs an investment decision.",
        "",
    ]

    if degraded:
        lines.extend(
            [
                "> ⚠️ **Degraded run.** No language-model provider was configured, so this "
                "analysis was produced by deterministic lexical rules. Interpretation of "
                "figures, semantic evidence adjudication and narrative synthesis were not "
                "performed.",
                "",
            ]
        )

    lines.extend(
        [
            "| | |",
            "|---|---|",
            f"| **Company** | {company_name or '—'} |",
            f"| **Source document** | {document_name or '—'} |",
            f"| **Generated** | {generated_at.strftime('%Y-%m-%d %H:%M UTC')} |",
            f"| **Scientific credibility** | **{report.overall_score:.1f} / 100** "
            f"({BAND_LABEL.get(band, band.value)}) |",
            f"| **Assessment confidence** | {report.confidence:.2f} |",
        ]
    )
    if scorecard:
        lines.append(
            f"| **IC recommendation** | {_humanise(scorecard.get('recommendation', ''))} |"
        )
    lines.extend(
        [
            "",
            "## Executive Summary",
            "",
            report.executive_summary.strip(),
            "",
        ]
    )

    if scorecard:
        lines.extend(_render_scorecard(scorecard))

    for section in sorted(report.sections, key=lambda s: s.get("order", 0)):
        lines.extend([f"## {section['heading']}", "", section["body_markdown"].strip(), ""])
        so_what = (section.get("so_what") or "").strip()
        if so_what:
            lines.extend([f"> **So what:** {so_what}", ""])
        confidence = (section.get("confidence") or "").strip()
        if confidence:
            reason = (section.get("confidence_reason") or "").strip()
            lines.extend(
                [
                    f"_Confidence: **{confidence}**" + (f" — {reason}" if reason else "") + "_",
                    "",
                ]
            )

    lines.extend(["## Recommendation", "", report.recommendation.strip(), ""])

    if report.citations:
        lines.extend(["## References", ""])
        for citation in report.citations:
            lines.append(_citation_line(citation))
        lines.append("")

    if report.limitations:
        lines.extend(["## Limitations of This Analysis", ""])
        lines.extend(f"- {limitation}" for limitation in report.limitations)
        lines.append("")

    lines.extend(
        [
            "---",
            "",
            "_BioIntel produces evidence-linked first drafts. Every claim above is traceable "
            "to a page of the source document, and every external citation to a retrieved "
            "record. Statements marked as BioIntel inference are analysis, not source facts._",
        ]
    )
    return "\n".join(lines)


def _citation_line(citation: dict[str, Any]) -> str:
    ref = citation.get("ref", "")
    if ref.startswith("C"):
        page = citation.get("page_number")
        quote = (citation.get("quote") or citation.get("statement") or "").strip()
        return f'- **[{ref}]** Source document, page {page}: "{quote}"'

    title = citation.get("title") or "Untitled record"
    label = citation.get("citation_label") or ""
    url = citation.get("url")
    journal = citation.get("journal")
    year = citation.get("year")
    venue = " · ".join(str(v) for v in (journal, year) if v)
    suffix = f" <{url}>" if url else ""
    return f"- **[{ref}]** {title}. {venue} ({label}).{suffix}".replace(" ()", "")


def render_html(
    report: BuiltReport,
    *,
    company_name: str | None = None,
    document_name: str | None = None,
    generated_at: dt.datetime | None = None,
    degraded: bool = False,
    scorecard: dict[str, Any] | None = None,
) -> str:
    markdown = render_markdown(
        report,
        company_name=company_name,
        document_name=document_name,
        generated_at=generated_at,
        degraded=degraded,
        scorecard=scorecard,
    )
    body = _md.render(markdown)
    band = report.overall_band
    accent = BAND_COLOR.get(band, "#334155")

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(report.title)}</title>
<style>
  :root {{ color-scheme: light dark; --accent: {accent}; }}
  * {{ box-sizing: border-box; }}
  body {{
    font: 16px/1.65 ui-serif, Georgia, "Times New Roman", serif;
    max-width: 46rem; margin: 0 auto; padding: 3rem 1.5rem 6rem;
    color: #111827; background: #ffffff;
  }}
  h1 {{ font-size: 2rem; line-height: 1.2; margin: 0 0 1.5rem; letter-spacing: -0.02em; }}
  h2 {{
    font-size: 1.3rem; margin: 2.75rem 0 0.75rem; padding-bottom: 0.35rem;
    border-bottom: 2px solid var(--accent); letter-spacing: -0.01em;
  }}
  h3 {{ font-size: 1.05rem; margin: 1.75rem 0 0.5rem; }}
  p, li {{ margin: 0 0 0.85rem; }}
  blockquote {{
    margin: 1.5rem 0; padding: 0.85rem 1.15rem; border-left: 4px solid var(--accent);
    background: #f8fafc; font-size: 0.94rem; font-family: ui-sans-serif, system-ui, sans-serif;
  }}
  table {{ border-collapse: collapse; width: 100%; margin: 1.25rem 0; font-size: 0.92rem;
           font-family: ui-sans-serif, system-ui, sans-serif; }}
  th, td {{ border: 1px solid #e2e8f0; padding: 0.5rem 0.7rem;
           text-align: left; vertical-align: top; }}
  th {{ background: #f1f5f9; font-weight: 600; }}
  code {{ font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.88em;
          background: #f1f5f9; padding: 0.1em 0.35em; border-radius: 3px; }}
  a {{ color: var(--accent); }}
  hr {{ border: none; border-top: 1px solid #e2e8f0; margin: 3rem 0 1.5rem; }}
  @media (prefers-color-scheme: dark) {{
    body {{ background: #0b0f19; color: #e5e7eb; }}
    blockquote {{ background: #111827; }}
    th {{ background: #111827; }}
    th, td {{ border-color: #1f2937; }}
    code {{ background: #111827; }}
  }}
  @media print {{
    body {{ max-width: none; padding: 0; }}
    h2 {{ page-break-after: avoid; }}
  }}
</style>
</head>
<body>
{body}
</body>
</html>
"""


def _render_scorecard(scorecard: dict[str, Any]) -> list[str]:
    """The ten-dimension scorecard as a markdown table.

    Rendered by BioIntel rather than written by the model, so the numbers in
    the memo are always the computed ones.
    """
    dimensions = scorecard.get("dimensions") or []
    if not dimensions:
        return []

    lines = [
        "## Investment Committee Scorecard",
        "",
        (
            "Scores are computed deterministically from the claim-level analysis. "
            "A dimension marked *not assessed* had no claims bearing on it — that is a gap "
            "in the deck, not a negative finding."
        ),
        "",
        "| Dimension | Score | Band | Confidence | What it answers |",
        "|---|---|---|---|---|",
    ]
    for dimension in dimensions:
        score = dimension.get("score")
        score_cell = f"**{score:.0f}**/100" if isinstance(score, int | float) else "—"
        band = _humanise(dimension.get("band") or "not assessed")
        confidence = _humanise(dimension.get("confidence_band") or "—")
        lines.append(
            f"| {dimension.get('label', '')} | {score_cell} | {band} | {confidence} | "
            f"{dimension.get('question', '')} |"
        )

    lines.extend(
        [
            "",
            f"**Company archetype:** {_humanise(scorecard.get('archetype', 'unknown'))} — "
            "dimension weighting is set by archetype, because a platform company and a "
            "single-asset company do not carry the same risks.",
            "",
            f"**Recommendation: {_humanise(scorecard.get('recommendation', ''))}.** "
            f"{scorecard.get('recommendation_rationale', '')}",
            "",
        ]
    )

    weak = [
        d
        for d in dimensions
        if isinstance(d.get("score"), int | float) and d["score"] < 50 and d.get("negative_drivers")
    ]
    if weak:
        lines.extend(["### What is holding the score down", ""])
        for dimension in weak[:4]:
            lines.append(f"- **{dimension.get('label')}** — {dimension.get('rationale', '')}")
            for driver in (dimension.get("negative_drivers") or [])[:2]:
                reason = driver.get("reason", "")
                ref = driver.get("claim_id", "")
                lines.append(f"  - {reason}" + (f" ({ref})" if ref else ""))
        lines.append("")

    return lines


def _humanise(value: str) -> str:
    return str(value).replace("_", " ").strip().capitalize() if value else "—"
