"""initial schema

Revision ID: 2e87a0e1da7f
Revises: 
Create Date: 2026-07-27 03:33:00.423414
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

import app.db.base

from sqlalchemy.dialects import postgresql

revision: str = '2e87a0e1da7f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('is_parsed', sa.Boolean(), nullable=False),
    sa.Column('requires_ocr', sa.Boolean(), nullable=False),
    sa.Column('pdf_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index('ix_documents_created_at', ['created_at'], unique=False)

    op.create_table('evidence_items',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('journal', sa.String(length=512), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('publication_date', sa.String(length=32), nullable=True),
    sa.Column('authors', app.db.base.StringList(), nullable=False),
    sa.Column('publication_types', app.db.base.StringList(), nullable=False),
    sa.Column('study_design', sa.String(length=48), nullable=False),
    sa.Column('mesh_terms', app.db.base.StringList(), nullable=False),
    sa.Column('keywords', app.db.base.StringList(), nullable=False),
    sa.Column('doi', sa.String(length=256), nullable=True),
    sa.Column('pmid', sa.String(length=32), nullable=True),
    sa.Column('pmcid', sa.String(length=32), nullable=True),
    sa.Column('nct_id', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('is_retracted', sa.Boolean(), nullable=False),
    sa.Column('is_preprint', sa.Boolean(), nullable=False),
    sa.Column('trial', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('fetched_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_items')),
    sa.UniqueConstraint('source', 'external_id', name='uq_evidence_items_source')
    )
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_items_nct_id'), ['nct_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_items_pmid'), ['pmid'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('locked_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_run_after'), ['run_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_jobs_status_run_after', ['status', 'run_after', 'priority'], unique=False)

    op.create_table('llm_call_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('stage', sa.String(length=48), nullable=True),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_call_logs'))
    )
    with op.batch_alter_table('llm_call_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_call_logs_run_id'), ['run_id'], unique=False)

    op.create_table('retrieval_cache',
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('request_url', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('fetched_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cache_key', name=op.f('pk_retrieval_cache'))
    )
    with op.batch_alter_table('retrieval_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retrieval_cache_expires_at'), ['expires_at'], unique=False)

    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_stage', sa.String(length=48), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('started_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_analysis_runs_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_runs'))
    )
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_runs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_status'), ['status'], unique=False)

    op.create_table('document_pages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('rotation', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('table_count', sa.Integer(), nullable=False),
    sa.Column('vector_drawing_count', sa.Integer(), nullable=False),
    sa.Column('image_area_ratio', sa.Float(), nullable=False),
    sa.Column('render_path', sa.String(length=1024), nullable=True),
    sa.Column('tables', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_pages_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_pages')),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_document_pages_document_id')
    )
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.create_index('ix_document_pages_doc_page', ['document_id', 'page_number'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('verbatim_quote', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.String(length=40), nullable=True),
    sa.Column('from_visual', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('claimed_evidence_tier', sa.String(length=32), nullable=False),
    sa.Column('quantitative', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_scientific', sa.Boolean(), nullable=False),
    sa.Column('is_falsifiable', sa.Boolean(), nullable=False),
    sa.Column('hedging_language', sa.Boolean(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('is_thesis_critical', sa.Boolean(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('quote_verification', sa.String(length=32), nullable=False),
    sa.Column('quote_match_score', sa.Float(), nullable=False),
    sa.Column('needs_human_review', sa.Boolean(), nullable=False),
    sa.Column('review_reasons', app.db.base.StringList(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('importance >= 0 AND importance <= 1', name=op.f('ck_claims_importance_range')),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], name=op.f('fk_claims_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_document_id'), ['document_id'], unique=False)
        batch_op.create_index('ix_claims_run_category', ['run_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_run_id'), ['run_id'], unique=False)

    op.create_table('company_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('company_name', sa.String(length=256), nullable=True),
    sa.Column('one_liner', sa.Text(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('headquarters', sa.String(length=256), nullable=True),
    sa.Column('company_stage', sa.String(length=64), nullable=True),
    sa.Column('lead_program', sa.String(length=256), nullable=True),
    sa.Column('lead_indication', sa.String(length=256), nullable=True),
    sa.Column('modality', sa.String(length=128), nullable=True),
    sa.Column('development_stage', sa.String(length=64), nullable=True),
    sa.Column('pipeline', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('team', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('funding', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('partnerships', app.db.base.StringList(), nullable=False),
    sa.Column('ip_position', sa.Text(), nullable=True),
    sa.Column('business_model', sa.Text(), nullable=True),
    sa.Column('stated_asks', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source_pages', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], name=op.f('fk_company_profiles_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_profiles')),
    sa.UniqueConstraint('run_id', name=op.f('uq_company_profiles_run_id'))
    )
    op.create_table('diligence_questions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('what_good_looks_like', sa.Text(), nullable=False),
    sa.Column('related_claim_ids', app.db.base.StringList(), nullable=False),
    sa.Column('related_evidence_ids', app.db.base.StringList(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], name=op.f('fk_diligence_questions_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diligence_questions'))
    )
    with op.batch_alter_table('diligence_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diligence_questions_run_id'), ['run_id'], unique=False)

    op.create_table('entities',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('normalized_key', sa.String(length=512), nullable=False),
    sa.Column('canonical_name', sa.String(length=512), nullable=True),
    sa.Column('aliases', app.db.base.StringList(), nullable=False),
    sa.Column('identifiers', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('role_in_program', sa.Text(), nullable=True),
    sa.Column('salience', sa.Float(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('source_pages', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], name=op.f('fk_entities_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
    sa.UniqueConstraint('run_id', 'entity_type', 'normalized_key', name='uq_entities_run_id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_normalized_key'), ['normalized_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_run_id'), ['run_id'], unique=False)

    op.create_table('page_blocks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('page_id', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('bbox', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('font_size', sa.Float(), nullable=False),
    sa.Column('is_bold', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['document_pages.id'], name=op.f('fk_page_blocks_page_id_document_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_blocks')),
    sa.UniqueConstraint('page_id', 'block_index', name='uq_page_blocks_page_id')
    )
    with op.batch_alter_table('page_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_blocks_document_id'), ['document_id'], unique=False)

    op.create_table('page_understandings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('page_id', sa.String(length=40), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('slide_title', sa.String(length=512), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('recovered_text', sa.Text(), nullable=False),
    sa.Column('visual_elements', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('data_points', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('tables', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('scientific_content', sa.Boolean(), nullable=False),
    sa.Column('used_vision', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['document_pages.id'], name=op.f('fk_page_understandings_page_id_document_pages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], name=op.f('fk_page_understandings_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_understandings')),
    sa.UniqueConstraint('run_id', 'page_id', name='uq_page_understandings_run_id')
    )
    with op.batch_alter_table('page_understandings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_understandings_run_id'), ['run_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('sections', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('overall_band', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('score_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('citations', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('limitations', app.db.base.StringList(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], name=op.f('fk_reports_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('run_id', name=op.f('uq_reports_run_id'))
    )
    op.create_table('run_stages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('stage', sa.String(length=48), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], name=op.f('fk_run_stages_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_stages')),
    sa.UniqueConstraint('run_id', 'stage', name='uq_run_stages_run_id')
    )
    with op.batch_alter_table('run_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_stages_run_id'), ['run_id'], unique=False)

    op.create_table('claim_assessments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('claim_id', sa.String(length=40), nullable=False),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('credibility_band', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('supporting_count', sa.Integer(), nullable=False),
    sa.Column('contradicting_count', sa.Integer(), nullable=False),
    sa.Column('neutral_count', sa.Integer(), nullable=False),
    sa.Column('best_supporting_evidence_id', sa.String(length=40), nullable=True),
    sa.Column('best_contradicting_evidence_id', sa.String(length=40), nullable=True),
    sa.Column('evidence_quality', sa.Float(), nullable=False),
    sa.Column('consistency', sa.Float(), nullable=False),
    sa.Column('novelty', sa.Float(), nullable=False),
    sa.Column('verdict', sa.Text(), nullable=False),
    sa.Column('key_uncertainties', app.db.base.StringList(), nullable=False),
    sa.Column('score_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_claim_assessments_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], name=op.f('fk_claim_assessments_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_assessments')),
    sa.UniqueConstraint('claim_id', name=op.f('uq_claim_assessments_claim_id'))
    )
    with op.batch_alter_table('claim_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_assessments_run_id'), ['run_id'], unique=False)

    op.create_table('claim_entities',
    sa.Column('claim_id', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_claim_entities_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_claim_entities_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_id', 'entity_id', name=op.f('pk_claim_entities'))
    )
    op.create_table('claim_evidence_links',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('claim_id', sa.String(length=40), nullable=False),
    sa.Column('evidence_id', sa.String(length=40), nullable=False),
    sa.Column('stance', sa.String(length=32), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('supporting_quote', sa.Text(), nullable=False),
    sa.Column('quote_verification', sa.String(length=32), nullable=False),
    sa.Column('quote_match_score', sa.Float(), nullable=False),
    sa.Column('caveats', app.db.base.StringList(), nullable=False),
    sa.Column('retrieval_query', sa.Text(), nullable=True),
    sa.Column('adjudicated_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_claim_evidence_links_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_items.id'], name=op.f('fk_claim_evidence_links_evidence_id_evidence_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], name=op.f('fk_claim_evidence_links_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_evidence_links')),
    sa.UniqueConstraint('run_id', 'claim_id', 'evidence_id', name='uq_claim_evidence_links_run_id')
    )
    with op.batch_alter_table('claim_evidence_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_evidence_links_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_evidence_links_evidence_id'), ['evidence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_evidence_links_run_id'), ['run_id'], unique=False)

    op.create_table('risk_flags',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('claim_id', sa.String(length=40), nullable=True),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('basis', sa.String(length=32), nullable=False),
    sa.Column('evidence_ids', app.db.base.StringList(), nullable=False),
    sa.Column('source_pages', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_rule_based', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_risk_flags_claim_id_claims'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], name=op.f('fk_risk_flags_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_flags'))
    )
    with op.batch_alter_table('risk_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_flags_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_flags_run_id'))

    op.drop_table('risk_flags')
    with op.batch_alter_table('claim_evidence_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_evidence_links_run_id'))
        batch_op.drop_index(batch_op.f('ix_claim_evidence_links_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_claim_evidence_links_claim_id'))

    op.drop_table('claim_evidence_links')
    op.drop_table('claim_entities')
    with op.batch_alter_table('claim_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_assessments_run_id'))

    op.drop_table('claim_assessments')
    with op.batch_alter_table('run_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_stages_run_id'))

    op.drop_table('run_stages')
    op.drop_table('reports')
    with op.batch_alter_table('page_understandings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_understandings_run_id'))

    op.drop_table('page_understandings')
    with op.batch_alter_table('page_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_blocks_document_id'))

    op.drop_table('page_blocks')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_run_id'))
        batch_op.drop_index(batch_op.f('ix_entities_normalized_key'))

    op.drop_table('entities')
    with op.batch_alter_table('diligence_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diligence_questions_run_id'))

    op.drop_table('diligence_questions')
    op.drop_table('company_profiles')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_run_id'))
        batch_op.drop_index('ix_claims_run_category')
        batch_op.drop_index(batch_op.f('ix_claims_document_id'))

    op.drop_table('claims')
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.drop_index('ix_document_pages_doc_page')

    op.drop_table('document_pages')
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_runs_status'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_document_id'))

    op.drop_table('analysis_runs')
    with op.batch_alter_table('retrieval_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retrieval_cache_expires_at'))

    op.drop_table('retrieval_cache')
    with op.batch_alter_table('llm_call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_run_id'))

    op.drop_table('llm_call_logs')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status_run_after')
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_run_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_run_after'))

    op.drop_table('jobs')
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_items_pmid'))
        batch_op.drop_index(batch_op.f('ix_evidence_items_nct_id'))

    op.drop_table('evidence_items')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('ix_documents_created_at')
        batch_op.drop_index(batch_op.f('ix_documents_content_hash'))

    op.drop_table('documents')
    # ### end Alembic commands ###
