"""claim types, corroboration status, IC scorecard

Revision ID: 7ae42a9019df
Revises: 2e87a0e1da7f
Create Date: 2026-07-27 14:49:45.030180
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

import app.db.base

from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

revision: str = "7ae42a9019df"
down_revision: str | None = "2e87a0e1da7f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("claim_assessments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("corroboration_status", sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column("corroboration_rationale", sa.Text(), nullable=False))
        batch_op.add_column(sa.Column("is_scorable", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("score_explanation", sa.Text(), nullable=False))
        batch_op.add_column(sa.Column("verification_status", sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column("verification_source", sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column("verification_detail", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("verification_identifiers", sa.JSON(), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_claim_assessments_corroboration_status"),
            ["corroboration_status"],
            unique=False,
        )

    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.add_column(sa.Column("claim_type", sa.String(length=48), nullable=False))
        batch_op.create_index(batch_op.f("ix_claims_claim_type"), ["claim_type"], unique=False)

    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "scorecard",
                sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "scientific_assessment",
                sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("ic_recommendation", sa.String(length=48), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_column("ic_recommendation")
        batch_op.drop_column("scientific_assessment")
        batch_op.drop_column("scorecard")

    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_claims_claim_type"))
        batch_op.drop_column("claim_type")

    with op.batch_alter_table("claim_assessments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_claim_assessments_corroboration_status"))
        batch_op.drop_column("verification_identifiers")
        batch_op.drop_column("verification_detail")
        batch_op.drop_column("verification_source")
        batch_op.drop_column("verification_status")
        batch_op.drop_column("score_explanation")
        batch_op.drop_column("is_scorable")
        batch_op.drop_column("corroboration_rationale")
        batch_op.drop_column("corroboration_status")

    # ### end Alembic commands ###
